name: 'Hola Mundo'
description: 'Saludar a alguien y guardar la fecha'
inputs:
  name:
    description: 'A quien saludar'
    required: true
outputs:
  time:
    description: 'Fecha'
runs:
  using: 'docker'
  image: 'Dockerfile'
  # args:
  #   - ${{ inputs.who-to-greet }}
